### ISSUE TITLE
为什么每一步不计算最后一个code id的loss

### ISSUE THREAD

**Issue by zhaijianyang** [PeterGriffinJin/LMIndexer#2]
![image](https://github.com/PeterGriffinJin/LMIndexer/assets/56312792/84e6a785-67f6-425a-9151-ce3a2fbc0392)

**Comment by PeterGriffinJin** [comment]
Hi there,

I'm sorry for not getting back to you sooner.

Code_id is not used in the loss calculation since it is a discrete value and cannot support back propagation. The quantized representation for this last code is "quantized_reps" which is used in calculating the reconstruction loss.

You can refer to Eq.6 in our paper.

Please feel free to let me know if you have other questions.

Best,
Bowen
